apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  labels:
    deploy: poi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - image: "registrybyd5320.azurecr.io/tripinsights/poi:1.0"
        imagePullPolicy: Always
        name: poi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        env:
        - name: WEB_PORT
          value: '80'
        - name: OPENAPI_DOCS_URI
          value: 'http://localhost'
        - name: DEBUG_LOGGING
          value: 'true'
        - name: SQL_USER
          value: 'sqladminbYd5320'
        - name: SQL_PASSWORD
          value: 'vP4kz8Mn4'
        - name: SQL_SERVER
          value: 'sqlserverbyd5320.database.windows.net'
        - name: SQL_DBNAME
          value: 'mydrivingDB'
        - name: WEB_SERVER_BASE_URI
          value: 'http://0.0.0.0'
        - name: ASPNETCORE_ENVIRONMENT
          value: 'Local'
        - name: CONFIG_FILES_PATH
          value: '/secrets'
