apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvtrips
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 20b2356d-0ba3-4c1d-965d-148a4af3e582
    keyvaultName: "kv-trips"              # the name of the KeyVault
    cloudName: "AzurePublicCloud"         # [OPTIONAL available for version > 0.0.4] if not provided, azure environment will default to AzurePublicCloud
    cloudEnvFileName: ""                  # [OPTIONAL available for version > 0.0.7] use to define path to file for populating azure environment
    objects:  |
      array:
        - |
          objectName: SQL-USER
          objectAlias: SQL_USER
          objectType: secret
          objectVersion: ""
          filePermission: 0755
        - |
          objectName: SQL-PASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret
          objectVersion: ""
          filePermission: 0755
        - |
          objectName: SQL-SERVER
          objectAlias: SQL_SERVER
          objectType: secret
          objectVersion: ""
          filePermission: 0755
        - |
          objectName: SQL-DBNAME
          objectAlias: SQL_DBNAME
          objectType: secret
          objectVersion: ""
          filePermission: 0755
    tenantId: "114228d5-6543-4f74-aaeb-234c77a2065"
