apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
  namespace: api
  labels:
    deploy: trips
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - image: "registrybyd5320.azurecr.io/tripinsights/trips:1.0"
        imagePullPolicy: Always
        name: trips
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        env:
        - name: PORT
          value: '80'
        - name: OPENAPI_DOCS_URI
          value: 'http://localhost'
        - name: DEBUG_LOGGING
          value: 'true'
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqluser
              key: SQL_USER 
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlpass
              key: SQL_PASSWORD 
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sqlserver
              key: SQL_SERVER 
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: sqldb
              key: SQL_DBNAME 
