apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: api
  labels:
    app: userprofile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: userprofile-container
        image : "registrybyd5320.azurecr.io/tripinsights/userprofile:1.0"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqluser
              key: SQL_USER 
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlpass
              key: SQL_PASSWORD 
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sqlserver
              key: SQL_SERVER 
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: sqldb
              key: SQL_DBNAME 
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  namespace: api
  labels:
    app: userprofile
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: userprofile

