kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-full-access
  namespace: web
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-full-access
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-user-full-access
subjects:
- kind: Group
  namespace: web
  name: 9655a662-8be3-411c-addb-1681cb812ae7
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-read-access
  namespace: api
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["list", "get"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-user-read-access
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-user-read-access
subjects:
- kind: Group
  namespace: api
  name: 9655a662-8be3-411c-addb-1681cb812ae7